# https://taskfile.dev

version: "3"

tasks:
  build-img:
    cmds:
      - git pull
      - ./img-gen.sh

  build-img-next:
    cmds:
      - git pull
      - ./img-gen-next.sh

  build-img-all:
    cmds:
      - git pull
      - ./img-gen.sh
      - ./img-gen-x.sh

  compile-kpatch:
    dir: kpatch
    cmds:
      - make clean all
      - mv kpatch ../files/board/arc/overlayfs/opt/arc/