# https://taskfile.dev

version: "3"

tasks:
  build-evo:
    cmds:
      - git reset --hard
      - git pull
      - ./img-gen.sh evo

  compile-kpatch:
    dir: kpatch
    cmds:
      - make clean all
      - mv kpatch ../files/p3/system/